name: hma-glacial-lakes
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.8
  - jupyter
  - bokeh
  - nbserverproxy
  - tornado
  - ipywidgets
  - graphviz
  - numpy=1.23.5 
  - scipy
  - pandas
  - geopandas
  - spatialpandas
  - shapely
  - netcdf4
  - configobj
  - xarray
  - pyviz_comms
  - param
  - numba
  - datashader
  - holoviews
  - geoviews
  - jinja2
  - hvplot
  - panel
  - parambokeh
  - ipympl
  - pip:
    - joblib
    - progressbar2
    - jupyter-panel-proxy
